name = "websocket-server"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

[vars]
# PostgreSQL connection string (for local development)
PG_CONNECTION_STRING = "postgresql://postgres:password@localhost:6432/todo-mvc-sync-postgres?sslmode=disable"
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
